require( 'sinatra' )
require( 'sinatra/contrib/all' )
require_relative( '../models/event' )
require_relative( '../models/client' )
require_relative( '../models/booking' )
also_reload( '../models/*' )
